### ISSUE TITLE
TypeError: 'float' object is not subscriptable (python 3.8)

### ISSUE THREAD

**Issue by stmlange** [mschwager/memunit#3]
Hello, thanks for this nice project.
Unfortunately the sample from the readme doesn't work on my side:
```
.venv/lib/python3.8/site-packages/memunit/__init__.py", line 23, in wrapper
    max_usage = round(mem_usage[0], 2)
TypeError: 'float' object is not subscriptable
```

Details:
```
$ pip freeze
memory-profiler==0.57.0
memunit==0.5.1
psutil==5.7.3
```

```
$ python --version
Python 3.8.0
```

```
$ head -n 5 /etc/os-release 
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.1"
```

Not quite sure what the root cause is, but it appears when specifying [`retval=True`](https://github.com/pythonprofilers/memory_profiler/blob/bd6da910f791cef725640fa207fb4ee433c93586/memory_profiler.py#L257) the memory profiler returns a tuple of (float, <return value>)

**Comment by stmlange** [comment]
I should also note that with `memunit-0.5.0` everything works fine, so I'll be using that for now. Thanks!

**Comment by mschwager** [comment]
Hi there,

Thanks for bringing this to my attention. Looks like this bug is a result of this change: https://github.com/pythonprofilers/memory_profiler/commit/1ecaf4edae1d84684dcc560df1e798aa7ed9a46d. In this PR https://github.com/mschwager/memunit/pull/2 the pinned `memory_profiler` dependency was updated, which resulted in the API returning a different type. Hence the `'float' object is not subscriptable` error. Looks like that change was first released in https://github.com/pythonprofilers/memory_profiler/releases/tag/v0.56.

I'll update the code to consider the changed return type :+1:

**Comment by mschwager** [comment]
The latest version includes a fix: https://pypi.org/project/memunit/0.5.2/
